### ISSUE TITLE
!Error in service definition http://192.168.1.8:80 urn:www-seagate-com:service:NAS:1

### ISSUE THREAD

**Issue by TonyPuryer** [yunuscadirci/CallStranger#20]
Attempting to run CallStranger on a Seagate Personal Cloud Nas and am getting the error:

`!Error in service definition http://192.168.1.8:80 urn:www-seagate-com:service:NAS:1
Traceback (most recent call last):
  File "CallStranger.py", line 115, in <module>
    print(colored(len(devices),'blue') , colored(' devices found:','blue'))
  File "/opt/lib/python3.8/site-packages/termcolor.py", line 110, in colored
    text = re.sub(COLORS_RE + '(.*?)' + RESET_RE, r'\1', text)
  File "/re.py", line 208, in sub
TypeError: expected string or bytes-like object
`

**Comment by yunuscadirci** [comment]
did you try latest commit?
