### ISSUE TITLE
No module named "setuptools"

### ISSUE THREAD

**Issue by moki2013** [yunuscadirci/CallStranger#23]
Attempting to install CallStranger on a Ubuntu 18.04.3 LTS device, and getting the error:

Traceback (most recent call last):
file "setup.py", line 1, in <module>
from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

**Comment by chipsnblip** [comment]
i'm running debian buster and installing the following packages did the trick: python3-setuptools python3-cryptography python3-requests python3-termcolor

**Comment by moki2013** [comment]
Thank you very much, it worked :-)
