### ISSUE TITLE
Only two devices found on the network

### ISSUE THREAD

**Issue by moki2013** [yunuscadirci/CallStranger#25]
Hi,

I have over 180 devices running on the same LAN (VMWare), all devices installed from the same template. CallStranger.py only shows two devices found, always the same two IP Addresses. 
Here's the output:

4  devices found:
 iRMCB55D19 http://192.168.2.54:50000 ( http://192.168.2.54:50000/ )
  0 service(s) found for iRMCB55D19
 iRMCB55D19 http://192.168.2.54:50000 ( http://192.168.2.54:50000/ )
  0 service(s) found for iRMCB55D19
 iRMCB55D1D http://192.168.2.58:50000 ( http://192.168.2.58:50000/ )
  0 service(s) found for iRMCB55D1D
 iRMCB55D1D http://192.168.2.58:50000 ( http://192.168.2.58:50000/ )
  0 service(s) found for iRMCB55D1D
 Total 0 service(s) found. do you want to continue to VERIFY if service(s) are vulnerable?

Why are the other computers not found, as long as they run the same OS, same GPO, same firewall settings, etc?

Thanks in advance.

**Comment by yunuscadirci** [comment]
They may be on other subnets. CallStranger.py uses SSDP. if you want to see devices on other networks, use CallDirect.py
