### ISSUE TITLE
Meaning of the output

### ISSUE THREAD

**Issue by firenux** [yunuscadirci/CallStranger#26]
Hi~!

Please can I ask meaning of words from output?

What do these mean from output of this program?
 1. Verified vulnerable services:
==> Does it mean services is vulnerable?
 2. Unverified  services:
==> Dose it mean services hasn't been verified from remote server?

Thanks.

**Comment by yunuscadirci** [comment]
Hi
Verified means your device succesfully sent NOTIFY traffic to external server
Unverified means server didn't get the traffic but we can't assure because it is not vulnerable or device expect some special header or value?
thansk
